#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::homePage

product_add:
    path: /add/product
    controller: App\Controller\ProductController::addProduct

user_register:
    path: /register
    controller: App\Controller\UserController::registerUser

user_activate:
    path: /user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        token: '[a-z0-9-]+'