#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::homePage

addProduct:
    path: /add/product
    controller: App\Controller\ProductController::addProduct

registerUser:
    path: /register/user
    controller: App\Controller\UserController::registerUser