#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{_locale}
    controller: App\Controller\DefaultController::homePage
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'

product_add:
    path: /{_locale}/add/product
    controller: App\Controller\ProductController::addProduct
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'

user_register:
    path: /{_locale}/register
    controller: App\Controller\UserController::registerUser
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'

user_activate:
    path: /user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        token: '[a-z0-9-]+'
        
product_list:
    path: /{_locale}/list/product
    controller: App\Controller\ProductController::listProduct
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'
        id: ^[0-9]+$

product_detail:
    path: /{_locale}/product/detail/{id}
    controller: App\Controller\ProductController::productDetail
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'
        
username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']

login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login
    
logout:
    path: /logout